dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

dependencies:
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    version: 0.6.6
    remappings:
      - '@aave=aave/protocol-v2@1.0.1'

networks:
  default: mainnet-fork-dev
  rinkeby:
    weth_token: '0xc778417E063141139Fce010982780140Aa0cD5Ab'
  mainnet-fork-dev: # mainnet for is for the fork test other technique from Mock test
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    lending_pool_address_provider: '0xb53c1a33016b2dc2ff3653530bff1848a515c8c5'
  kovan:
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    lending_pool_address_provider: '0x88757f2f99175387ab4c6a4b3067c77a695b0349' 

# Search Weth Token Etherscan Rinkeby
# Search Weth Token Etherscan (for mainnet)


# Search Lending Pool Address Provider
