dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  rinkeby:
    weth_token: '0xc778417E063141139Fce010982780140Aa0cD5Ab'
  mainnet-fork-dev: # mainnet for is for the fork test other technique from Mock test
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
  

# Search Weth Token Etherscan Rinkeby
# Search Weth Token Etherscan (for mainnet)
