dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    version: 0.8.0
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
networks:
  default: development
  rinkeby:
    verify: True
  mainnet-fork-dev: # mainnet for is for the fork test other technique from Mock test
    verify: False
  development:  
    verify: False
  ganache-local:
    verify: False

