dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    version: 0.8.0
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
networks:
  default: development
  rinkeby:
    verify: True
  kovan:      # we are using kovan because weth_token only supports kovan testnet
    verify: True
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    fau_token: '0xFab46E002BbF0b4509813474841E0716E6730136'
    dai_usd_price_feed: '0x777A68032a88E5A84678A77Af2CD65A7b3c0775a'
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
  mainnet-fork-dev: # mainnet for is for the fork test other technique from Mock test
    verify: False   # we add all addresses of kovan for testing otherwise need to add mainnet addresses there
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    fau_token: '0xFab46E002BbF0b4509813474841E0716E6730136'
    dai_usd_price_feed: '0x777A68032a88E5A84678A77Af2CD65A7b3c0775a'
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
  development:  
    verify: False
  ganache-local:
    verify: False


# To get weth_token search weth_token address testnet etherscan
# To get fau_token => erc20faucet.com
# add mint free token from erc20faucet then add it's contract address to your import token then fau token will show in your account balance


